%YAML:1.0
net: "supervisionCNN.prototxt"
weights: "bvlc_alexnet.caffemodel"
number_of_levels: 7
svm: "linear_svm.xml"
filter_size: [ 7, 11 ]
stride: 1
test_data: "/home/dolotov_e/FDDB/FDDB-folds/FDDB-fold-01.txt"
test_data_folder: "/home/dolotov_e/FDDB/"
result_file: "fold-01-out.txt"
